# fly.toml app configuration file generated for vietnamese-translation on 2025-03-10T15:30:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vietnamese-translation"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
